apiVersion: v2
appVersion: auto
dependencies:
- name: common
  repository: https://truecharts.org/
  version: 3.5.8
- name: traefik
  repository: https://helm.traefik.io/traefik
  version: 9.19.1
deprecated: false
description: A Traefik based Reverse Proxy and Certificate Manager
home: https://github.com/truecharts/apps/tree/master/charts/stable/traefik
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
keywords:
- traefik
- ingress
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: truecharts.org
- email: kjeld@schouten-lebbing.nl
  name: Ornias1993
  url: truecharts.org
name: traefik
sources:
- https://github.com/traefik/traefik
- https://github.com/traefik/traefik-helm-chart
- https://traefik.io/
type: application
version: 4.0.6
